### ISSUE TITLE
Pedalboard Request Daddario XPND1 and XPND2

### ISSUE THREAD

**Issue by matt-latt** [PedalPlayground/PedalPlayground.github.io#1204]
XPND1
https://www.daddario.com/products/accessories/xpnd-pedalboards/01-xpnd-pedalboard/item/daddario-xpnd-pedalboard-01-9893/
Dimensions retracted (W x H x D): 34.92 x 6.53 x 14.86 cm (13.75" x 2.57" x 5.85")
Extended dimensions (W x H x D): 62.67 x 6.53 x 14.86 cm (24.75" x 2.57" x 5.85")

XPND2
https://www.daddario.com/products/accessories/xpnd-pedalboards/01-xpnd-pedalboard/item/daddario-xpnd-pedalboard-02-9894/
Retracted dimensions (W x H x D): 44.45 x 9.9 x 32.5 cm (17.5" x 3.9" x 12.8")
Extended dimensions (W x H x D): 80.65 x 9.9 x 32.5 cm (31.75" x 3.9 x 12.8")

**Comment by phil-co** [comment]
There is an issue with the dimensions of the XPND2 pedalboard. While the smallest retracted size is 17.5", the size of just the larger side of the XPND2 alone is actually 16.75" (I measured my own unit). The extra 0.75" in the retracted size is the small bit of the smaller expanding side that sticks out, since it cannot retract 100%.

If you could resize the larger side down to 16.75", it would be appreciated. Thanks!
