### ISSUE TITLE
Case-sensitive duplicate

### ISSUE THREAD

**Issue by AdrianDAlessandro** [PedalPlayground/PedalPlayground.github.io#225]
I just cloned my fork of this repo and was presented with a warning about the Source Audio Collider images. It appears there are two copies of the same image. The `/public/data/pedals.json` file references the lowercase option.
<img width="668" alt="Screenshot 2020-10-03 at 14 46 17" src="https://user-images.githubusercontent.com/40875798/94993317-fd1a1180-0587-11eb-8ff4-33137a559d44.png">

**Comment by tehtrav** [comment]
fixed

**Comment by jayrgee** [comment]
@tehtrav [app/images/pedals/SA-collider.png](https://github.com/PedalPlayground/PedalPlayground.github.io/blob/master/app/images/pedals/SA-collider.png) was [not deleted](https://github.com/PedalPlayground/PedalPlayground.github.io/commit/a753c4e39c6676a73f84c0d57305062434f2a4a5).
Fixed by [PR#291](https://github.com/PedalPlayground/PedalPlayground.github.io/pull/291)
